name: lint
on:
  push:
  pull_request:

jobs:
  golangci:
    name: "Run linter (golangci-lint)"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"

      - name: "Run golangci-lint"
        id: "run-linter"
        uses: "golangci/golangci-lint-action@v3"
